### ISSUE TITLE
Array.Empty should not be included for .NET 4.6 and .NET Core 1.0 and above builds.

### ISSUE THREAD

**Issue by NN---** [rsdn/CodeJam#115]
**Describe the bug**
.NET 4.6 and .NET Core 1.0 have Array.Empty.
This creates ambiguity.

**To Reproduce**
```cs
using CodeJam.Collections;
using System;

var a = Array.Empty<int>();
```

**Expected behavior**
No ambiguity

**Comment by ndrwrbgs** [comment]
Could you revise the issue to clarify that `Array` (the class) is the problem and not `.Empty` (which would be resolved based on however you directed the language to resolve `Array`)?

**Comment by ndrwrbgs** [comment]
@NN--- , could you try reproducing the issue in full rather than a snippet? This looks impossible since there isn't an `Array` in this library, there is only `Array<T>`.
