### ISSUE TITLE
Update NuGet

### ISSUE THREAD

**Issue by NN---** [rsdn/CodeJam#122]
@andrewvk  @ig-sinicyn Can you update NuGet ?

**Comment by andrewvk** [comment]
You mean to release a new version?

**Comment by NN---** [comment]
Yes :)

**Comment by NN---** [comment]
@andrewvk  @ig-sinicyn  Any update ?

**Comment by ig-sinicyn** [comment]
@NN--- 
Sorry, I'm quite busy this week. @andrewvk can you release the update?

**Comment by andrewvk** [comment]
I am also very busy for now. Maybe at the weekend, but I am not sure.

**Comment by NN---** [comment]
Can I help ?

**Comment by andrewvk** [comment]
You can prepare everything required for the release. See if there are any new R# warnings, add release notes to a readme, correct the version number in build files. See commits with a "Prepare xxx" comment for an example.

**Comment by NN---** [comment]
There are plenty of warnings , suggestions and hints:
![image](https://user-images.githubusercontent.com/580536/98662908-15ccd280-2351-11eb-916a-84fd0f5259cc.png)

Do we need to analyze the code in the tests projects ?
Perhaps it can be ignored there.

**Comment by NN---** [comment]
https://github.com/rsdn/CodeJam/commit/b0313520e9296157c0649ee6b77a2dee4fcfa964

**Comment by NN---** [comment]
@andrewvk Can we release now ?:)

**Comment by andrewvk** [comment]
> There are plenty of warnings , suggestions and hints:
> ![image](https://user-images.githubusercontent.com/580536/98662908-15ccd280-2351-11eb-916a-84fd0f5259cc.png)
> 
> Do we need to analyze the code in the tests projects ?
> Perhaps it can be ignored there.

I only check the Main project usually

**Comment by andrewvk** [comment]
Done
