### ISSUE TITLE
[Net 5.0] Behavior changes in string comparison

### ISSUE THREAD

**Issue by ig-sinicyn** [rsdn/CodeJam#125]
Scan for 
CA1307: Specify StringComparison for clarity
CA1309: Use ordinal StringComparison
and fix tests

more detail on https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus

**Comment by NN---** [comment]
The simplest way is to add analyzers

```xml

    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

and suppress everything we don't need in editorconfig

```
dotnet_diagnostic.csXXXX.severity=none
```

**Comment by NN---** [comment]
With .NET 5 btw you don’t even need the NuGet :)

**Comment by NN---** [comment]
I am not sure what exactly the library should do. In most cases you do want the current culture.
