### ISSUE TITLE
QueryableExtensions for ranges generates wrong Expression.

### ISSUE THREAD

**Issue by sdanyliv** [rsdn/CodeJam#144]
This line
https://github.com/rsdn/CodeJam/blob/master/CodeJam.Main/Collections/QueryableExtensions.Ranges.cs#L192

generates `And` but should be `AndAlso`. It should be not not bit operation but predicate.

**Comment by NN---** [comment]
Can you think about failing test case with the current implementation ?
Thanks.

https://github.com/rsdn/CodeJam/blob/master/CodeJam.Main.Tests/Collections/QueryableExtensionsTests.cs

**Comment by sdanyliv** [comment]
Well in bit operations it works, but when generated SQL, it creates also working but ineffective query.

**Comment by sdanyliv** [comment]
No time, otherwise I'll just propose PR. I've seen this bug accidentally when analysed generated expression tree.
