### ISSUE TITLE
Please add [CanBeNull] attribute to some methods

### ISSUE THREAD

**Issue by MozgC** [rsdn/CodeJam#36]
For example this method:
```c#
    [Pure]
    public static TValue GetValueOrDefault<TKey, TValue>([NotNull] this Dictionary<TKey, TValue> dictionary, TKey key)
    {
      return DictionaryExtensions.GetValueOrDefault<TKey, TValue>(dictionary, key, default (TValue));
    }
```
should have [CanBeNull] attribute applied, because it can return null when TValue is a class.
Otherwise ReSharper does not help catch possible null reference exception.

**Comment by Lexey** [comment]
[NotNull] here means that the dictionary itself cannot be null. Nothing to fix there.

**Comment by MozgC** [comment]
```c#
var dict = new Dictionary<int, List<int>>();
var nullList = dict.GetValueOrDefault(777); // nullList is now null
var x = nullList.FirstOrDefault(); // An exception will occur here. But ReSharper doesn't warn about the exception. But if you add [CanBeNull] attribute to the whole GetValueOrDefault() method, then ReSharper will know that the method can return null and will warn the user.
```

**Comment by ig-sinicyn** [comment]
@Lexey, OP is talking about marking the return value with `[CanBeNull]`. it looks reasonable for me.

@MozgC, will do. BTW doing a PR would work too:)

**Comment by ig-sinicyn** [comment]
@MozgC  I've marked only overloads that have no selector or explicit default value arg.  If this is not what you want - let me know:)

**Comment by MozgC** [comment]
@ig-sinicyn, awesome, thank you!
