### ISSUE TITLE
Extensions ideas from other libraries

### ISSUE THREAD

**Issue by NN---** [rsdn/CodeJam#41]
What is currently covered in CodeJam from this list ?
What do you think can be integrated into CodeJam ?

https://github.com/dahall/Vanara/tree/master/Core/Extensions

**Comment by andrewvk** [comment]
BitHelper - nothing covered
Enum - all currently covered
FileTime - nothing covered
IO - nothing covered. May be useful. But, IMHO, unsafe + md cache must be used instead of Marshal
Marshal - nothing. Very specific
Reflection - mostly covered
String - interop specific
