### ISSUE TITLE
Fix deprecated licenseUrl

### ISSUE THREAD

**Issue by NN---** [rsdn/CodeJam#59]
```
C:\Program Files\dotnet\sdk\2.1.500\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(202,5): warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'licens
e' element instead. [CodeJam\Main\src\CodeJam.Main.csproj]
```

See: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties

-    License URL will be removed from project properties and PackageLicenseUrl will be removed from the project file.
-    Project properties will have License type (free text field that can take an SPDX expression) and License file (free text field that can take a path to the license file on disk relative to the project file)
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>

-    License file

```xml
    <PropertyGroup>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="licenses\LICENSE.txt" Pack="true" PackagePath="$(PackageLicenseFile)"/>
    </ItemGroup>
```

**Comment by ig-sinicyn** [comment]
Fixed with CJ-cleanup commit
