### ISSUE TITLE
Make license available in GitHub

### ISSUE THREAD

**Issue by NN---** [rsdn/CodeJam#77]
GitHub doesn't show MIT license for CodeJam: 
![image](https://user-images.githubusercontent.com/580536/52225378-ddae7b00-28b2-11e9-8ff5-e4a2101ded8e.png)

**Comment by NN---** [comment]
Maybe it is in the project settings ?
Here license works well:
https://github.com/jquery/jquery

**Comment by andrewvk** [comment]
There are no these settings

**Comment by NN---** [comment]
Fixed by a00f2bd9c9e16aa54675e215945f89719cdc7087 :)
